# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.cache/wt [current_project]
set_property parent.project_path D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/sin1024.coe
read_verilog -library xil_defaultlib {
  D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/new/encode.v
  D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/new/gen_wave_data.v
  D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/new/hdmi_background.v
  D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/new/hdmi_trans.v
  D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/new/parallel_to_serial.v
  D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/new/wave_mix.v
  D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/new/adda_top.v
}
read_ip -quiet D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/dpram_8x1024/dpram_8x1024.xci
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/dpram_8x1024/dpram_8x1024_ooc.xdc]

read_ip -quiet D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/rom8x1024/rom8x1024.xci
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/rom8x1024/rom8x1024_ooc.xdc]

read_ip -quiet D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/hdmi_clock/hdmi_clock.xci
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/hdmi_clock/hdmi_clock_board.xdc]
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/hdmi_clock/hdmi_clock.xdc]
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/hdmi_clock/hdmi_clock_ooc.xdc]

read_ip -quiet D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/clock/clock.xci
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/clock/clock_board.xdc]
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/clock/clock.xdc]
set_property used_in_implementation false [get_files -all d:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/sources_1/ip/clock/clock_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/constrs_1/new/top_pin.xdc
set_property used_in_implementation false [get_files D:/my_space/01_FPGA_demo_7020/Lab14_FPGA_adda_hdmi/adda_hdmi.srcs/constrs_1/new/top_pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top adda_hdmi_top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef adda_hdmi_top.dcp
create_report "synth_3_synth_report_utilization_0" "report_utilization -file adda_hdmi_top_utilization_synth.rpt -pb adda_hdmi_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
