# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/dpram_8x1024/dpram_8x1024.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpram_8x1024 || ORIG_REF_NAME==dpram_8x1024} -quiet] -quiet

# IP: ip/rom8x1024/rom8x1024.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom8x1024 || ORIG_REF_NAME==rom8x1024} -quiet] -quiet

# IP: ip/hdmi_clock/hdmi_clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_clock || ORIG_REF_NAME==hdmi_clock} -quiet] -quiet

# IP: ip/clock/clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] -quiet
