######################################################################
#
# File name : tb_ram_pp_compile.do
# Created on: Tue May 12 10:25:26 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../ram_pp.srcs/sources_1/ip/ram_wr256x8_rd256x8/sim/ram_wr256x8_rd256x8.v" \
"../../../../ram_pp.srcs/sources_1/new/ram_pp.v" \
"../../../../ram_pp.srcs/sim_1/new/tb_ram_pp.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

