######################################################################
#
# File name : tb_ram_pp_wave.do
# Created on: Tue May 12 10:25:30 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
