######################################################################
#
# File name : tb_pll_led_compile.do
# Created on: Thu Jul 02 17:37:49 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../pll.srcs/sources_1/ip/clock" \
"../../../../pll.srcs/sources_1/ip/clock/clock_clk_wiz.v" \
"../../../../pll.srcs/sources_1/ip/clock/clock.v" \
"../../../../pll.srcs/sources_1/new/pll_led.v" \
"../../../tb_pll_led.v" \


# compile glbl module
C:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

#quit -force

