######################################################################
#
# File name : tb_pll_led_simulate.do
# Created on: Thu Jul 02 17:37:53 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_pll_led xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_pll_led_wave.do}

view wave
view structure
view signals

do {tb_pll_led.udo}

run 1000ns
