######################################################################
#
# File name : tb_pll_led_wave.do
# Created on: Thu Jul 02 17:36:23 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
