######################################################################
#
# File name : tb_fifo_test_simulate.do
# Created on: Tue May 12 10:18:42 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_fifo_test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_fifo_test_wave.do}

view wave
view structure
view signals

do {tb_fifo_test.udo}

run 1000ns
