######################################################################
#
# File name : tb_fifo_test_compile.do
# Created on: Tue May 12 10:18:37 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../fifo_test.srcs/sources_1/ip/asfifo_wr256x8_rd256x8/asfifo_wr256x8_rd256x8_sim_netlist.v" \
"../../../../fifo_test.srcs/sources_1/new/fifo_test.v" \
"../../../../fifo_test.srcs/sim_1/new/tb_fifo_test.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

