######################################################################
#
# File name : tb_fifo_test.udo
# Created on: Mon Mar 23 16:47:06 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
