######################################################################
#
# File name : tb_fifo_test_wave.do
# Created on: Mon Mar 23 16:47:06 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
