# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/ila_ad/ila_ad.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_ad || ORIG_REF_NAME==ila_ad} -quiet] -quiet

# IP: ip/ila_da/ila_da.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_da || ORIG_REF_NAME==ila_da} -quiet] -quiet

# IP: ip/rom8x512/rom8x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom8x512 || ORIG_REF_NAME==rom8x512} -quiet] -quiet
