# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/hdmi_out/hdmi_out.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out || ORIG_REF_NAME==hdmi_out} -quiet] -quiet

# IP: ip/clock/clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] -quiet

# XDC: ip/hdmi_out/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out || ORIG_REF_NAME==hdmi_out} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/hdmi_out/src/rgb2dvi_ooc.xdc

# XDC: ip/hdmi_out/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out || ORIG_REF_NAME==hdmi_out} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/clock/clock_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clock/clock.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clock/clock_ooc.xdc
