# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/clock/clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock || ORIG_REF_NAME==clock} -quiet] -quiet
