# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/system_ov5640_axis_3_0.xci
# IP: The module: 'system_ov5640_axis_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/src/ip/cmos_in_buf.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf} -quiet] -quiet

# XDC: c:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/src/ip/cmos_in_buf.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/src/ip/cmos_in_buf_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/system_ov5640_axis_3_0.xci
# IP: The module: 'system_ov5640_axis_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/src/ip/cmos_in_buf.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf} -quiet] -quiet

# XDC: c:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/src/ip/cmos_in_buf.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/mp02/Desktop/mz7020_ov5640_quad/ov5640_quad/ov5640_quad.srcs/sources_1/bd/system/ip/system_ov5640_axis_3_0/src/ip/cmos_in_buf_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmos_in_buf || ORIG_REF_NAME==cmos_in_buf} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
