# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/demo/Z7-Lite/7020/FPGA/Lab12_FPGA_LCD_img/lcd_img.srcs/sources_1/ip/rom_image/rom_image.xci
# IP: The module: 'rom_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/demo/Z7-Lite/7020/FPGA/Lab12_FPGA_LCD_img/lcd_img.srcs/sources_1/ip/rom_image/rom_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/demo/Z7-Lite/7020/FPGA/Lab12_FPGA_LCD_img/lcd_img.srcs/sources_1/ip/rom_image/rom_image.xci
# IP: The module: 'rom_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/demo/Z7-Lite/7020/FPGA/Lab12_FPGA_LCD_img/lcd_img.srcs/sources_1/ip/rom_image/rom_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
